### PR TITLE
ether to lgum caption changes

### PR DESCRIPTION
**Pull request by z2akhtar**

### CODE REVIEW

**Comment by ashwaths1** [comment]
@z2akhtar The changes looks good but I am not inclined to click the Merge button, we need to test this and this cant go into Master right now

**Comment by ashwaths1** [comment]
@z2akhtar Awesome if you have tested it well. Can you put the documentation and the test cases on github?

**Comment by z2akhtar** [comment]
@ashwaths1 https://ledgerium.atlassian.net/browse/LB-38?focusedCommentId=10144&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10144

**Comment by FaysalM** [comment]
Looks like we will be changing to XLG instead of lgum.

**Pull request closed without merging**
